apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantum-project-finance-2.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quantum
  template:
    metadata:
      labels:
        app: quantum
    spec:
      containers:
      - name: solver
        image: quantum/project-finance-2.0:latest
