apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantum-rd-acceleration-vqe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quantum
  template:
    metadata:
      labels:
        app: quantum
    spec:
      containers:
      - name: solver
        image: quantum/rd-acceleration-vqe:latest
